#!/command/with-contenv sh
# vi: ft=sh
exec 2>&1

if [ -z "$CADDY_TARGET" ]; then
  echo "ERROR: The environment variable CADDY_TARGET must be set"
  exit 1
fi

if [ -z "$TS_HOSTNAME" ]; then
  echo "ERROR: The environment variable TS_HOSTNAME must be set"
  exit 1
fi

if [ -z "$TS_TAILNET" ]; then
  echo "ERROR: The environment variable TS_TAILNET must be set"
  exit 1
fi

cat > /etc/caddy/Caddyfile << CADDYFILE
$TS_HOSTNAME.$TS_TAILNET.ts.net
reverse_proxy $CADDY_TARGET
forward_auth unix//run/tailscale.nginx-auth.sock {
  uri /auth
  header_up Remote-Addr {remote_host}
  header_up Remote-Port {remote_port}
  header_up Original-URI {uri}
  copy_headers {
		Tailscale-User>X-Webauth-User
		Tailscale-User>X-Webauth-User
		Tailscale-Name>X-Webauth-Name
		Tailscale-Login>X-Webauth-Login
		Tailscale-Tailnet>X-Webauth-Tailnet
		Tailscale-Profile-Picture>X-Webauth-Profile-Picture
	}
}
CADDYFILE

exec /usr/local/bin/caddy run --config=/etc/caddy/Caddyfile
